### PR TITLE
Fix unicode character display in message

### LINKED ISSUE #205: When trying to request with Emojis in message, they're not correctly encoded
## Scope

- Go to "Request" and insert an Emoji in the message
- Have someone else scan your QR code
- Note how on their device the emoji now has become a bunch of random letters and symbols (probably something specific to the encoding of the QR code)

## Deliverables

- Make Emojis and essentially all Unicode characters work in `<RequestFunds />`

## Roles
bounty gardener: @TimDaub / 10%
bounty worker: name / 75%
bounty reviewer: name / 15%

### PR DESCRIPTION
**Pull request by MaxStalker**
Fixes #205
Visual confirmation can be found below: 

image

### CODE REVIEW

**Comment by MaxStalker** [comment]
Was checking this thoroughly yesterday. Just checked again with exactly the same flow as you described with this test string:
```I need a 🖼 of a ♀🦄 riding ♂🐱‍🐉 on a ✈```
Works as intended.
Can you check you are on correct branch?

File: src/components/SendToAddress.js [hunk 1]
```diff
@@ -103,7 +103,13 @@ export default class SendToAddress extends React.Component {
 
   componentWillReceiveProps(newProps) {
     if (this.props.scannerState !== newProps.scannerState) {
-        this.setState(Object.assign(this.state, newProps.scannerState))
+        const { message,...rest } = newProps.scannerState;
+
+        this.setState({
+          ...this.state,
+          ...rest,
+          message: decodeURI(message)
```
Comment (TimDaub) [inline src/components/SendToAddress.js]: Not sure if this lifecycle function is still necessary.
On my machine (I tested multiple times), it `this.props.scannerState !== newProps.scannerState` is never true. Hence I never see an emoji but encoded gibberish.

Additionally, since on SendByAddress.js, the QR scan button is "hidden", we don't expect scannerState to change any time within the life of SendByAddress.js.

My recommendation would hence be to cast `decodeURI` in the component's constructor.

**Comment by TimDaub** [comment]
> Works as intended.
> Can you check you are on correct branch?

Definitely on the correct branch, I also debugged the code and it's definitely not calling `decodeURI`. I left a comment on why I believe this is the case.

File: src/components/SendToAddress.js (hunk 1 above)
Comment (MaxStalker) [reply src/components/SendToAddress.js]: Erm... that button is right there over the blockie...
Or you were trying to scan the code from main view?

Comment (TimDaub) [reply src/components/SendToAddress.js]: Ahhh now I see the problem. OK when I click 
Screen Shot 2019-07-15 at 16 44 38 in SendToAddress it works perfectly.

But when I click

Screen Shot 2019-07-15 at 16 45 00

It doesn't work. That's the bug!

Comment (MaxStalker) [reply src/components/SendToAddress.js]: Nice spot! :)
I forgot about this flow ^__^

**Comment by MaxStalker** [comment]
> Instead of making sure to call `decodeURI` in every component, we could also simply call it in "SendByScan" [here](https://github.com/leapdao/plasma-burner-wallet/blob/master/src/components/SendByScan.js#L114). Just want to make sure that future users of "SendByScan" don't make the same mistake.
> 
> Thoughts?

That's actually really smart! I've added those changes in latest commit
