### PR TITLE
Set default currency on first boot

### LINKED ISSUE #248: Transfer fails if default currency is not set in the settings
# Description
I tried to use https://s.peep.cash/ from an incognito session, and I got this error when trying to transfer 1 pDAI:
image

And this in the console:
image

I noticed that if you change the currency preference from dollars to euros, the problem is gone. You can also do dollars to euros, and back to dollars again, and it works.

This is happening because there is no default setting for the currency.

## Steps to reproduce
- open a new incognito window to https://s.peep.cash/
- transfer some pDAI from another wallet to this new wallet
- transfer some pDAI from the new wallet to some other address
- :boom: 

# Solution
Make it work :)

# Roles
- Gardener: @vrde / 30%
- Worker: ? / 55%
- Reviewer: ? / 15%

### PR DESCRIPTION
**Pull request by vrde**
Fix #248

### CODE REVIEW

**Comment by TimDaub** [comment]
Would you mind explaining what the bug was here?

Because as far as I know, we've always set the default currency on first
boot. So I'm wondering why it stopped working suddenly...

File: src/App.js [hunk 1]
```diff
@@ -471,11 +465,9 @@ export default class App extends Component {
       //}, false)
     }
     if (prevState.account !== account){
-      const currency = getStoredValue('currency');
-      if (currency){
-        storeValues({currency}, account);
-        eraseStoredValue('currency');
-      }
+      const currency = getStoredValue('currency') || CONFIG.CURRENCY.DEFAULT_CURRENCY;
```
Comment (TimDaub) [inline src/App.js]:
```suggestion
      const currency =  getStoredValue('currency', account) || getStoredValue('currency') || CONFIG.CURRENCY.DEFAULT_CURRENCY;
```
