### PR TITLE
Fix Use react-i18next instead of i18n #173

### LINKED ISSUE #173: Use react-i18next instead of i18n
## Scope

- The burner-wallet currently uses i18next directly
- There is however an npm module called react-i18next, that allows direct translation by defining components
- This e.g. allows to translate a text with an `<a />` tag. A problem we encountered [here](https://github.com/leapdao/burner-wallet/pull/164#pullrequestreview-256304878)

## Deliverables

- Investigate react-i18next and see if it fits our use case
- If it does, replace all occurrences of i18next with react-i18next in the burner-wallet

As an example:

```
<div>
  {i18n.t("hello_world")}
</div>
```

should be replaced with an appropriate react-i18next equivalent. 

## Notes

Please also take a look at #140.

## Gains for the project

- Better translation for the users of the burner-wallet
- More efficient translation for developers

## Roles
bounty gardener: @TimDaub / 10%
bounty worker: name / 75%
bounty reviewer: name / 15%

### PR DESCRIPTION
**Pull request by iamonuwa**
Fixes #173

Will rebase https://github.com/social-dist0rtion-protocol/planet-a/ to fix https://github.com/social-dist0rtion-protocol/planet-a/issues/47 once this has been merged

### CODE REVIEW

File: src/components/BurnWallet.js [hunk 1]
```diff
@@ -1,35 +1,39 @@
...
-      </div>
-      <div style={{textAlign:"center",marginTop:20,width:"100%",fontWeight:'bold',fontSize:20}}>
-        {i18n.t('burn_wallet.disclaimer')}
-      </div>
-      <div>
-        <Ruler/>
-        <div className="content ops row">
+    <Translation>
+      {(t) => (
+		  <>
```
Comment (MaxStalker) [inline src/components/BurnWallet.js]: Something wrong with spacing here as well.
Also, why we aren't using withTranslation HOC for this file?

File: src/components/Bity.js [hunk 2]
```diff
@@ -359,26 +360,28 @@ class Bity extends Component {
...
-            <a
-              href="https://bity.com/"
-              target="_blank"
-              rel="noopener noreferrer"
-            >
-              bity.com
-            </a>
-            , the secure swiss crypto gateway. No KYC is required within
-            bity.com's 5000 CHF (~4500 EUR) annual limit.
+            <Trans i18nKey="offramp.heading">
```
Comment (MaxStalker) [inline src/components/Bity.js]: Formatting is messed up here

File: src/components/MainCard.js [hunk 3]
```diff
@@ -1,34 +1,32 @@
 import React from "react";
 import { Flex, Icon, Box } from "rimble-ui";
-import i18next from "i18next";
+import { withTranslation} from 'react-i18next';
```
Comment (MaxStalker) [inline src/components/MainCard.js]: Missing space before bracket

File: src/components/Receive.js [hunk 4]
```diff
@@ -42,9 +43,11 @@ export default class Receive extends React.Component {
             </Box>
           </CopyToClipboard>
           <div style={{width:"100%",textAlign:'center',padding:20}}>
-            <a href={CONFIG.SIDECHAIN.EXPLORER.URL + "address/" + address} target="_blank" rel="noopener noreferrer">
-              View on {CONFIG.SIDECHAIN.EXPLORER.NAME}
-            </a>
+			<Trans i18nKey="receive.view_link">
```
Comment (MaxStalker) [inline src/components/Receive.js]: Check spacing here

File: src/components/SendToAddress.js [hunk 5]
```diff
@@ -54,7 +54,7 @@ export default class SendToAddress extends React.Component {
       // NOTE: In this case, we scan the RequestFunds QR code and if "currency"
       // is missing, we display a warning.
       } else if (((toAddress && amount) || message) && !currency) {
-        changeAlert({type: "warning", message: i18n.t("send_to_address.currency_error")});
+        changeAlert({type: "warning", message: this.props.t("send_to_address.currency_error")});
```
Comment (MaxStalker) [inline src/components/SendToAddress.js]: No need for `this` keyword here, since we are in a constructor

File: src/components/SendToAddress.js [hunk 6]
```diff
@@ -237,15 +237,28 @@ export default class SendToAddress extends React.Component {
         })
       }
     }else{
-      this.props.changeAlert({type: 'warning', message: i18n.t('send_to_address.error')})
+      this.props.changeAlert({type: 'warning', message: this.props.t('send_to_address.error')})
```
Comment (MaxStalker) [inline src/components/SendToAddress.js]: We can put `t` in a destructuring brackets on line 163

File: src/components/SendToAddress.js [hunk 7]
```diff
@@ -282,17 +296,17 @@ export default class SendToAddress extends React.Component {
           type="number"
           readOnly
           placeholder={this.props.currencyDisplay(0)}
-          value={this.state.amount}
+          value={this.commaFormatted(this.state.amount)}
           ref={(input) => { this.amountInput = input; }}
-          onChange={event => this.updateState('amount', event.target.value)}
+		  onChange={event => this.updateState('amount', event.target.value)}
```
Comment (MaxStalker) [inline src/components/SendToAddress.js]: Wrong spacing

File: src/components/SendToAddress.js [hunk 8]
```diff
@@ -237,15 +237,28 @@ export default class SendToAddress extends React.Component {
         })
       }
     }else{
-      this.props.changeAlert({type: 'warning', message: i18n.t('send_to_address.error')})
+      this.props.changeAlert({type: 'warning', message: this.props.t('send_to_address.error')})
     }
   };
 
+  onKeyDown = e => {
```
Comment (MaxStalker) [inline src/components/SendToAddress.js]: Please, don't do this! 😕
This is super bad UX since you are blocking all the shortcuts - like "select all" and copy/pasting.

File: src/components/SendToAddress.js [hunk 9]
```diff
@@ -268,11 +281,12 @@ export default class SendToAddress extends React.Component {
     let amountInputDisplay = (
       <Input
         width={1}
-        type="number"
+        type="text"
         placeholder={this.props.currencyDisplay(0)}
         value={this.state.amount}
         ref={(input) => { this.amountInput = input; }}
-        onChange={event => this.updateState('amount', event.target.value)}
+		onChange={event => this.updateState('amount', event.target.value)}
```
Comment (MaxStalker) [inline src/components/SendToAddress.js]: Wrong spacing here

File: src/components/SendToAddress.js [hunk 10]
```diff
@@ -268,11 +281,12 @@ export default class SendToAddress extends React.Component {
     let amountInputDisplay = (
       <Input
         width={1}
-        type="number"
+        type="text"
```
Comment (MaxStalker) [inline src/components/SendToAddress.js]: Why we want to change type of the input here?

File: src/components/WithdrawFromPrivate.js [hunk 11]
```diff
@@ -110,13 +110,13 @@ export default class SendToAddress extends React.Component {
           message: 'Withdrawn!'
         });
     }else{
-      this.props.changeAlert({type: 'warning', message: i18n.t('withdraw_from_private.error')})
+      this.props.changeAlert({type: 'warning', message: this.props.t('withdraw_from_private.error')})
```
Comment (MaxStalker) [inline src/components/WithdrawFromPrivate.js]: Move to destructuring brackets on line 74

File: src/components/Exchange.js [hunk 12]
```diff
@@ -74,13 +74,13 @@ export default class Exchange extends React.Component {
       xdaiMetaAccount: xdaiMetaAccount,
       daiToXdaiMode: false,
       ethToDaiMode: false,
-      loaderBarStatusText: i18n.t('loading'),
+      loaderBarStatusText: this.props.t('loading'),
```
Comment (MaxStalker) [inline src/components/Exchange.js]: No need for `this` in constructor

File: src/components/Exchange.js [hunk 13]
```diff
@@ -74,13 +74,13 @@ export default class Exchange extends React.Component {
...
       loaderBarStartTime:Date.now(),
       loaderBarPercent: 2,
       loaderBarColor: "#aaaaaa",
       gwei: 5,
       maxWithdrawlAmount: 0.00,
-      withdrawalExplanation: i18n.t('exchange.withdrawal_explanation'),
+      withdrawalExplanation: this.props.t('exchange.withdrawal_explanation'),
```
Comment (MaxStalker) [inline src/components/Exchange.js]: No need for `this` in constructor

File: src/App.js [hunk 14]
```diff
@@ -833,690 +833,695 @@ export default class App extends Component {
...
-                  ...state,
-                  gwei
-                })
-              }}
-              />
-              <div id="context" className={"context"}></div>
-              {eventParser}
-            </div>
-          </div>
+          <Translation>
```
Comment (MaxStalker) [inline src/App.js]: Huge diff again, man. I don't realy want check it line-by-line again here...
Please, ask gardener to triple-check that it works as intended. And if he's ok - go merge it.

And before that fix the spacing, it's completly screwed.

File: src/components/SendToAddress.js (hunk 10 above)
Comment (iamonuwa) [reply src/components/SendToAddress.js]: To allow commas, you need to use text but disable text inputs

File: src/App.js (hunk 14 above)
Comment (iamonuwa) [reply src/App.js]: I get you. But it totally works.

Comment (iamonuwa) [reply src/App.js]: I get you. But it totally works

File: src/components/SendToAddress.js (hunk 10 above)
Comment (MaxStalker) [reply src/components/SendToAddress.js]: Just checked in codepen:
https://codepen.io/maxstalker-the-animator/pen/aeqyBP

Both commas and periods work with `type="number"` on Chrome, Firefox and Safari on iOS. On top of that Firefox will even format number properly.

File: src/App.js (hunk 14 above)
Comment (MaxStalker) [reply src/App.js]: @TimDaub you will need to verify this 👆

File: src/components/SendToAddress.js (hunk 8 above)
Comment (iamonuwa) [reply src/components/SendToAddress.js]: What do you suggest?

File: src/components/SendToAddress.js (hunk 9 above)
Comment (iamonuwa) [reply src/components/SendToAddress.js]: Can't reproduce this locally

File: src/components/SendToAddress.js (hunk 10 above)
Comment (iamonuwa) [reply src/components/SendToAddress.js]: The number type doesn't allow comma on the input field

Comment (MaxStalker) [reply src/components/SendToAddress.js]: I wouldn't suggest without checking thoroughly :|
https://www.loom.com/share/0bf7a60873744a3ea29397edcc073c1e

File: src/components/SendToAddress.js (hunk 8 above)
Comment (MaxStalker) [reply src/components/SendToAddress.js]: Validate input, show error below it if it doesn't comply with current locale and enable/disable button - will work 10x better than ignoring keystrokes.
Also you can change value to locale formatted, when field is losing focus, but not when user is inputting something. Especially, when we don't show any pattern on how it should properly be.

File: src/components/SendToAddress.js (hunk 9 above)
Comment (MaxStalker) [reply src/components/SendToAddress.js]: There is 8 spaces in original code and 2 tabs in yours. See the problem here?

File: src/components/SendToAddress.js [hunk 15]
```diff
@@ -31,7 +31,8 @@ class SendToAddress extends React.Component {
         },
         convertCurrency,
         changeAlert,
-        address,
+		address,
```
Comment (MaxStalker) [inline src/components/SendToAddress.js]: Spacing here?

File: src/components/SendToAddress.js [hunk 16]
```diff
@@ -237,15 +238,28 @@ export default class SendToAddress extends React.Component {
         })
       }
     }else{
-      this.props.changeAlert({type: 'warning', message: i18n.t('send_to_address.error')})
+      this.props.changeAlert({type: 'warning', message: t('send_to_address.error')})
     }
   };
 
+  onKeyDown(e) {
```
Comment (TimDaub) [inline src/components/SendToAddress.js]: Am I right in assuming that you're checking `,` and `.` with this?
Honestly, I believe this a very fragile way of addressing the problem as it depends on the inputs of a user and their device.

Let's say someone uses a text-to-speech device to input this data, then your code wouldn't work.

I hence recommend to: Allow the user to use their preferred way of typing floating point numbers (it's their freedom to use `,` or `.`).

In the back of the application, we then parse these values to what makes sense to web3.

File: src/components/SendToAddress.js (hunk 10 above)
Comment (TimDaub) [reply src/components/SendToAddress.js]: @iamonuwa What language is your browser set to? Maybe yours doesn't allow commas in the input fields? Let's try to get to the bottom of this!

This post might be helpful: https://www.ctrl.blog/entry/html5-input-number-localization.html

In general, I'd always defer to what the WC3 recommends in this case!

Comment (iamonuwa) [reply src/components/SendToAddress.js]: > @iamonuwa What language is your browser set to? And what browser are you using? Maybe yours doesn't allow commas in the input fields? Let's try to get to the bottom of this!
> 
> This post might be helpful: https://www.ctrl.blog/entry/html5-input-number-localization.html
> 
> In general, I'd always defer to what the WC3 recommends in this case!

I've removed this to fix the current i18next issue as proposed by the issue. I'll now work on https://github.com/social-dist0rtion-protocol/planet-a/issues/47 as a separate PR
